"""create initial tables

Revision ID: 1b847c7aa315
Revises: ad6e3877263b
Create Date: 2026-07-21 20:56:10.916361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b847c7aa315'
down_revision: Union[str, Sequence[str], None] = 'ad6e3877263b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_payments_payment_id'), 'bot_payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_bot_payments_telegram_id'), 'bot_payments', ['telegram_id'], unique=False)
    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('vpn_subscription_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bypass_subscription_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vpn_client_id', sa.String(length=255), nullable=True),
    sa.Column('last_reminder_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_users_telegram_id'), 'bot_users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_users_telegram_id'), table_name='bot_users')
    op.drop_table('bot_users')
    op.drop_index(op.f('ix_bot_payments_telegram_id'), table_name='bot_payments')
    op.drop_index(op.f('ix_bot_payments_payment_id'), table_name='bot_payments')
    op.drop_table('bot_payments')
    # ### end Alembic commands ###
