"""change_datetime_to_timestamptz

Revision ID: 2247f6987e2b
Revises: 0df6c15cd3bc
Create Date: 2026-05-09 14:09:33.243642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2247f6987e2b'
down_revision: Union[str, Sequence[str], None] = '0df6c15cd3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
