"""sync_models

Revision ID: 2d181d352915
Revises: d924e42a8796
Create Date: 2026-05-17 14:11:11.728721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d181d352915'
down_revision: Union[str, Sequence[str], None] = 'd924e42a8796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_bot_payments_payment_id'), table_name='bot_payments')
    op.create_foreign_key(None, 'bot_users', 'vpn_servers', ['server_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot_users', type_='foreignkey')
    op.create_index(op.f('idx_bot_payments_payment_id'), 'bot_payments', ['payment_id'], unique=True)
    # ### end Alembic commands ###
