"""add_sub_port_to_vpn_servers

Revision ID: 3246abdc6ea6
Revises: 6953e4cd0216
Create Date: 2026-05-10 11:08:15.730884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3246abdc6ea6'
down_revision: Union[str, Sequence[str], None] = '6953e4cd0216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_servers', sa.Column('sub_port', sa.Integer(), nullable=False, server_default='2096'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_servers', 'sub_port')
    # ### end Alembic commands ###
