"""add_unique_yookassa_payment_id

Revision ID: 4485a7019807
Revises: 947623f791ef
Create Date: 2026-05-18 20:59:50.657934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4485a7019807'
down_revision: Union[str, Sequence[str], None] = '947623f791ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_users_vpn_subscription_end'), table_name='bot_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bot_users_vpn_subscription_end'), 'bot_users', ['vpn_subscription_end'], unique=False)
    # ### end Alembic commands ###
