"""add index on vpn_client_id

Revision ID: 575c94820dfd
Revises: 0e72736a48e3
Create Date: 2026-06-30 11:42:31.170656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575c94820dfd'
down_revision: Union[str, Sequence[str], None] = '0e72736a48e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_users_vpn_subscription_end'), table_name='bot_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bot_users_vpn_subscription_end'), 'bot_users', ['vpn_subscription_end'], unique=False)
    # ### end Alembic commands ###
