"""add_api_path_to_vpn_servers

Revision ID: 6953e4cd0216
Revises: 6bb857551750
Create Date: 2026-05-10 10:41:15.494841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6953e4cd0216'
down_revision: Union[str, Sequence[str], None] = '6bb857551750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vpn_servers', sa.Column('api_path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vpn_servers', 'api_path')
    # ### end Alembic commands ###
