"""expand_bot_payment_fields

Revision ID: 9d7c22fdde04
Revises: 5c8283b80743
Create Date: 2026-06-24 10:31:19.066493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7c22fdde04'
down_revision: Union[str, Sequence[str], None] = '5c8283b80743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_payments', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('bot_payments', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('bot_payments', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('bot_payments', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('bot_payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_bot_payments_telegram_id'), 'bot_payments', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_payments_telegram_id'), table_name='bot_payments')
    op.drop_column('bot_payments', 'updated_at')
    op.drop_column('bot_payments', 'is_paid')
    op.drop_column('bot_payments', 'status')
    op.drop_column('bot_payments', 'currency')
    op.drop_column('bot_payments', 'amount')
    # ### end Alembic commands ###
