"""Add email and username to clients table

Revision ID: ad562bb4d859
Revises: af606f0c2378
Create Date: 2026-04-29 15:40:57.833863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad562bb4d859'
down_revision: Union[str, Sequence[str], None] = 'af606f0c2378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('clients', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('username', sa.String(length=100), nullable=False))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('clients_user_id_key'), 'clients', type_='unique')
    op.drop_column('clients', 'id')
    op.drop_column('clients', 'updated_at')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('clients_user_id_key'), 'clients', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('clients', 'username')
    op.drop_column('clients', 'email')
    op.drop_column('clients', 'client_id')
    # ### end Alembic commands ###
