"""init_squashed

Revision ID: ad6e3877263b
Revises: 
Create Date: 2026-07-11 15:40:54.546825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6e3877263b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_users_vpn_client_id'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_vpn_subscription_end'), table_name='bot_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bot_users_vpn_subscription_end'), 'bot_users', ['vpn_subscription_end'], unique=False)
    op.create_index(op.f('ix_bot_users_vpn_client_id'), 'bot_users', ['vpn_client_id'], unique=False)
    # ### end Alembic commands ###
